### ISSUE TITLE
Tseytin transformation complicates formulas that are already in CNF

### ISSUE THREAD

**Issue by markasoftware** [guicho271828/cl-sat#9]
For example: `(cl-sat:to-cnf '(or a b))` yields

```
(AND CL-SAT.AUX-VARIABLES::A0 (OR CL-SAT.AUX-VARIABLES::A0 (NOT B))
     (OR CL-SAT.AUX-VARIABLES::A0 (NOT A))
     (OR (NOT CL-SAT.AUX-VARIABLES::A0) A B))
```

It would be great to only perform the expansion when necessary. For my use-case, I have a few million clauses, but only about 1000 variables, so adding so many auxiliary variables can be a big deal.

**Comment by guicho271828** [comment]
(to-cnf form #'to-cnf-naive)
